language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install coveralls
script:
  coverage run --source=bankcsvtoqif -m unittest bankcsvtoqif/tests/test_banks.py bankcsvtoqif/tests/test_smartlabeler.py bankcsvtoqif/tests/test_transaction.py
after_success:
  coveralls
